apiVersion: apps/v1
kind: Deployment
metadata:
  name: forceworkbench-web
  labels:
    app: forceworkbench
    process: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forceworkbench
      process: web
  template:
    metadata:
      labels:
        app: forceworkbench
        process: web
    spec:
      volumes:
        - name: forceworkbench-config
          configMap:
            name: forceworkbench-config
        - name: forceworkbench-secrets
          secret:
            secretName: forceworkbench-secrets
      containers:
        - name: forceworkbench-web
          image: ryanbrainard/forceworkbench:45.0.0
          imagePullPolicy: Always
          command:
            - vendor/bin/heroku-php-apache2
          args:
            - workbench
          env:
            - name: PORT
              value: '80'
            - name: forceworkbench__redisUrl__default
              value: redis://forceworkbench-redis:6379
            - name: forceworkbench__sessionStore__default
              value: redis://forceworkbench-redis:6379
          volumeMounts:
            - name: forceworkbench-config
              mountPath: /app/workbench/config/overrides.php
              subPath: overrides.php
            - name: forceworkbench-secrets
              mountPath: /app/workbench/configOverrides.php # TODO: update app to read from /config/secrets.php
              subPath: secrets.php
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: healthcheck.php

